// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2UdwUCjBAhw8vkcFdfkWjvW245Owa0Bg',
    appId: '1:773919947043:web:cef1939e5f39f7e5863496',
    messagingSenderId: '773919947043',
    projectId: 'chat-app-8c586',
    authDomain: 'chat-app-8c586.firebaseapp.com',
    storageBucket: 'chat-app-8c586.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCOf0q34qiu5ut-yJZZ5nWyEO8Cp9OmOQ',
    appId: '1:773919947043:android:b99387f31302e572863496',
    messagingSenderId: '773919947043',
    projectId: 'chat-app-8c586',
    storageBucket: 'chat-app-8c586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHU-6eBRKI8FRAl4Hkw5fA5Yj5QNVO7VM',
    appId: '1:773919947043:ios:2db6945fc7251900863496',
    messagingSenderId: '773919947043',
    projectId: 'chat-app-8c586',
    storageBucket: 'chat-app-8c586.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHU-6eBRKI8FRAl4Hkw5fA5Yj5QNVO7VM',
    appId: '1:773919947043:ios:2db6945fc7251900863496',
    messagingSenderId: '773919947043',
    projectId: 'chat-app-8c586',
    storageBucket: 'chat-app-8c586.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2UdwUCjBAhw8vkcFdfkWjvW245Owa0Bg',
    appId: '1:773919947043:web:f29a65b4e8310553863496',
    messagingSenderId: '773919947043',
    projectId: 'chat-app-8c586',
    authDomain: 'chat-app-8c586.firebaseapp.com',
    storageBucket: 'chat-app-8c586.appspot.com',
  );
}
